### ISSUE TITLE
error on composer install/update

### ISSUE THREAD

**Issue by venkycc** [anod/gmail-imap-php#4]
Hello

Is this code still maintained?

Do i need to worry about the following errors when i install via composer?

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.`

Thanks

**Comment by anod** [comment]
`Package container-interop/container-interop is abandoned`

Zend Imap library, which is this library built on top, is **not maintained anymore**, my library still works, but I have no plans to migrate to another solution

`Package phpunit/phpunit-mock-objects is abandoned`
I've updated phpunit to the latest version to fix the warning
